#!/bin/bash
NUM=20000000
INPUT_DIRECTORY="$1"
TEMP_DIRECTORY="./temp"
OUTPUT_DIRECTORY="./Sampled_ucsd_merged"

# Check if input directory is provided
if [[ -z $INPUT_DIRECTORY ]]; then
    echo "Input directory not provided. Please provide the input directory as a command-line argument."
    exit 1
fi

# Create temp directory if it does not exist
if [[ ! -d "$TEMP_DIRECTORY" ]]; then
    mkdir "$TEMP_DIRECTORY"
fi

# Create output directory if it does not exist
if [[ ! -d "$OUTPUT_DIRECTORY" ]]; then
    mkdir "$OUTPUT_DIRECTORY"
fi

# Loop through the files in the input directory
for FILE in "$INPUT_DIRECTORY"/*; do
    if [[ $FILE == *.fastq.gz ]]; then
        # Check if file has already been processed
        BASENAME=$(basename "$FILE" .fastq.gz)
        OUTPUT_FILE="$OUTPUT_DIRECTORY/$BASENAME.sampled.fastq.gz"
        if [[ -f "$OUTPUT_FILE" ]]; then
            echo "Output file $OUTPUT_FILE already exists. Skipping to the next file."
            continue
        fi

        # Perform the action on the file using seqtk
        echo "Performing action on file $FILE..."
        seqtk sample -s100 "$FILE" $NUM > "$OUTPUT_DIRECTORY/$BASENAME.sampled.fastq.gz"
        echo "Action completed on file $FILE."
    fi
done
